-- Seed categories + professions (from trouvepro-professions.json)
insert into public.categories(id,name_fr,name_en) values('construction','Construction et rénovation','Construction & Renovation') on conflict(id) do nothing;
insert into public.categories(id,name_fr,name_en) values('mechanical_electrical','Électricité, plomberie et CVAC','Electrical, Plumbing & HVAC') on conflict(id) do nothing;
insert into public.categories(id,name_fr,name_en) values('home_services','Services résidentiels','Home Services') on conflict(id) do nothing;
insert into public.categories(id,name_fr,name_en) values('cleaning','Nettoyage et entretien','Cleaning') on conflict(id) do nothing;
insert into public.categories(id,name_fr,name_en) values('outdoor','Extérieur et saisonnier','Outdoor & Seasonal') on conflict(id) do nothing;
insert into public.categories(id,name_fr,name_en) values('automotive','Automobile','Automotive') on conflict(id) do nothing;
insert into public.categories(id,name_fr,name_en) values('beauty','Beauté et bien-être','Beauty & Wellness') on conflict(id) do nothing;
insert into public.categories(id,name_fr,name_en) values('health_care','Santé et soins','Health & Care') on conflict(id) do nothing;
insert into public.categories(id,name_fr,name_en) values('education','Éducation et tutorat','Education & Tutoring') on conflict(id) do nothing;
insert into public.categories(id,name_fr,name_en) values('professional','Services professionnels','Professional Services') on conflict(id) do nothing;
insert into public.categories(id,name_fr,name_en) values('technology','Technologie','Technology') on conflict(id) do nothing;
insert into public.categories(id,name_fr,name_en) values('events','Événements et créatif','Events & Creative') on conflict(id) do nothing;
insert into public.categories(id,name_fr,name_en) values('pets','Animaux','Pets & Animals') on conflict(id) do nothing;
insert into public.categories(id,name_fr,name_en) values('moving_transport','Déménagement et transport','Moving & Transport') on conflict(id) do nothing;
insert into public.categories(id,name_fr,name_en) values('textile_misc','Couture et divers','Sewing & Misc') on conflict(id) do nothing;

insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Entrepreneur général','General contractor','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Charpenterie-menuiserie','Framing & carpentry','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Fondations','Foundations','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Maçonnerie','Masonry','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Béton et coffrage','Concrete & formwork','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Excavation','Excavation','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Couvreur (toiture)','Roofing','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Imperméabilisation','Waterproofing','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Isolation','Insulation','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Gypse et plâtrage','Drywall & plastering','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Pose de revêtements de sol','Flooring installation','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Céramique et carrelage','Tiling & ceramics','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Peinture (entrepreneur)','Painting (contractor)','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Portes et fenêtres (installation)','Doors & windows (installation)','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Charpente métallique','Structural steel','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('construction','Ébénisterie et armoires','Cabinetry & millwork','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('mechanical_electrical','Électricien','Electrician','rbq','RBQ + CMEQ');
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('mechanical_electrical','Plomberie','Plumbing','rbq','RBQ + CMMTQ');
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('mechanical_electrical','Chauffage','Heating','rbq','RBQ + CMMTQ');
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('mechanical_electrical','Ventilation et climatisation (CVAC)','Ventilation & air conditioning (HVAC)','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('mechanical_electrical','Réfrigération','Refrigeration','rbq',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('home_services','Homme à tout faire (petits travaux)','Handyman (small jobs)','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('home_services','Montage de meubles','Furniture assembly','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('home_services','Réparation de portes et fenêtres','Doors & windows repair','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('home_services','Réparation d''électroménagers','Appliance repair','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('home_services','Serrurier','Locksmith','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('home_services','Nettoyage de gouttières','Gutter cleaning','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('home_services','Lavage à pression','Pressure washing','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('home_services','Nettoyage de conduits et filtres','Duct & filter cleaning','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('cleaning','Ménage résidentiel','Residential cleaning','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('cleaning','Entretien commercial','Commercial cleaning','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('cleaning','Grand ménage','Deep cleaning','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('cleaning','Nettoyage de tapis','Carpet cleaning','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('cleaning','Lavage de vitres','Window washing','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('cleaning','Nettoyage après construction','Post-construction cleaning','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('outdoor','Aménagement paysager','Landscaping','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('outdoor','Entretien de pelouse','Lawn care','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('outdoor','Jardinage','Gardening','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('outdoor','Déneigement','Snow removal','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('outdoor','Émondage et abattage d''arbres','Tree trimming & removal','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('outdoor','Installation de clôtures','Fence installation','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('outdoor','Terrasses et patios','Decks & patios','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('outdoor','Entretien de piscine','Pool maintenance','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('automotive','Mécanicien (garagiste)','Mechanic','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('automotive','Mécanicien mobile','Mobile mechanic','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('automotive','Carrosserie','Auto body','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('automotive','Service de pneus','Tire service','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('automotive','Esthétique automobile','Auto detailing','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('automotive','Réparation de pare-brise','Windshield repair','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('beauty','Coiffeur(se)','Hairdresser','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('beauty','Barbier','Barber','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('beauty','Maquilleur(se)','Makeup artist','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('beauty','Esthéticien(ne)','Esthetician','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('beauty','Pose d''ongles','Nail technician','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('beauty','Extensions de cils','Eyelash extensions','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('beauty','Massothérapeute','Massage therapist','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('beauty','Entraîneur(se) personnel(le)','Personal trainer','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('health_care','Infirmier(ère)','Nurse','order','OIIQ (titre protégé)');
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('health_care','Préposé(e) aux bénéficiaires','Care aide','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('health_care','Aide à domicile','Home care aide','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('health_care','Soins aux aînés','Elderly care','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('health_care','Garde d''enfants','Childcare / babysitting','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('health_care','Physiothérapeute','Physiotherapist','order','OPPQ (titre protégé)');
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('health_care','Nutritionniste-diététiste','Dietitian-nutritionist','order','ODNQ (titre protégé)');
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('education','Tuteur(trice) scolaire','Academic tutor','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('education','Professeur de langue','Language teacher','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('education','Cours de musique','Music lessons','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('education','Préparation aux examens','Test preparation','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('education','Moniteur(trice) de conduite','Driving instructor','other','SAAQ (école reconnue)');
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('professional','Teneur(se) de livres','Bookkeeper','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('professional','Préparation de déclarations d''impôts','Tax preparation','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('professional','Comptable (CPA)','Accountant (CPA)','order','CPA (titre protégé)');
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('professional','Consultant(e)','Consultant','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('professional','Traduction','Translation','','OTTIAQ pour titre « traducteur agréé »');
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('professional','Courtier immobilier','Real estate broker','other','OACIQ');
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('professional','Notaire','Notary','order','Chambre des notaires (titre protégé)');
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('professional','Avocat(e)','Lawyer','order','Barreau (titre protégé)');
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('technology','Soutien informatique','IT support','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('technology','Réparation d''ordinateurs','Computer repair','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('technology','Réparation de téléphones','Phone repair','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('technology','Développeur web','Web developer','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('technology','Graphiste','Graphic designer','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('technology','Gestionnaire de médias sociaux','Social media manager','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('events','Photographe','Photographer','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('events','Vidéaste','Videographer','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('events','Traiteur','Caterer','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('events','Organisateur(trice) d''événements','Event planner','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('events','DJ','DJ','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('events','Musicien(ne)','Musician','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('events','Fleuriste','Florist','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('pets','Promeneur(se) de chiens','Dog walker','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('pets','Gardien(ne) d''animaux','Pet sitter','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('pets','Toiletteur(se)','Pet groomer','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('pets','Éducateur(trice) canin','Dog trainer','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('pets','Vétérinaire','Veterinarian','order','OMVQ (titre protégé)');
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('moving_transport','Déménageur','Mover','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('moving_transport','Livraison','Delivery','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('moving_transport','Enlèvement de débris','Junk removal','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('moving_transport','Transport léger','Light hauling','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('textile_misc','Couturier(ère) / Retouches','Tailor / Alterations','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('textile_misc','Rembourrage','Upholstery','',null);
insert into public.professions(category_id,name_fr,name_en,licence,licence_note) values('textile_misc','Cordonnier','Shoe repair','',null);
